# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from decompai_client.models.analysis_source import AnalysisSource
from decompai_client.models.analysis_type import AnalysisType
from typing import Optional, Set
from typing_extensions import Self

class AnalysisAcceptedEvent(BaseModel):
    """
    Fired when analysis is started.
    """ # noqa: E501
    event_type: Optional[StrictStr] = 'Analysis - Accepted'
    timestamp: StrictInt
    start_source: AnalysisSource
    analysis_type: Optional[AnalysisType]
    user_prompt: StrictBool
    __properties: ClassVar[List[str]] = ["event_type", "timestamp", "start_source", "analysis_type", "user_prompt"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Analysis - Accepted']):
            raise ValueError("must be one of enum values ('Analysis - Accepted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalysisAcceptedEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if analysis_type (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_type is None and "analysis_type" in self.model_fields_set:
            _dict['analysis_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalysisAcceptedEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_type": obj.get("event_type") if obj.get("event_type") is not None else 'Analysis - Accepted',
            "timestamp": obj.get("timestamp"),
            "start_source": obj.get("start_source"),
            "analysis_type": obj.get("analysis_type"),
            "user_prompt": obj.get("user_prompt")
        })
        return _obj


