# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AnalysisSource(str, Enum):
    """
    AnalysisSource
    """

    """
    allowed enum values
    """
    NEW_FILE_OPEN = 'New File Open'
    TOOLBAR_ICON_REQUEST = 'Toolbar Icon Request'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnalysisSource from a JSON string"""
        return cls(json.loads(json_str))


