# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from decompai_client.models.decompiler import Decompiler
from decompai_client.models.original_languages import OriginalLanguages
from typing import Optional, Set
from typing_extensions import Self

class BinaryDetails(BaseModel):
    """
    Binary-level parameters. Fixed at binary creation time.
    """ # noqa: E501
    instructions: Optional[StrictStr] = None
    original_languages: Optional[OriginalLanguages] = None
    platform: Optional[StrictStr] = None
    os_version: Optional[StrictStr] = None
    input_file_sha256: Optional[StrictStr] = None
    decompiler: Optional[Decompiler] = None
    __properties: ClassVar[List[str]] = ["instructions", "original_languages", "platform", "os_version", "input_file_sha256", "decompiler"]

    @field_validator('platform')
    def platform_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ios', 'macos']):
            raise ValueError("must be one of enum values ('ios', 'macos')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BinaryDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of original_languages
        if self.original_languages:
            _dict['original_languages'] = self.original_languages.to_dict()
        # override the default output from pydantic by calling `to_dict()` of decompiler
        if self.decompiler:
            _dict['decompiler'] = self.decompiler.to_dict()
        # set to None if instructions (nullable) is None
        # and model_fields_set contains the field
        if self.instructions is None and "instructions" in self.model_fields_set:
            _dict['instructions'] = None

        # set to None if platform (nullable) is None
        # and model_fields_set contains the field
        if self.platform is None and "platform" in self.model_fields_set:
            _dict['platform'] = None

        # set to None if os_version (nullable) is None
        # and model_fields_set contains the field
        if self.os_version is None and "os_version" in self.model_fields_set:
            _dict['os_version'] = None

        # set to None if input_file_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.input_file_sha256 is None and "input_file_sha256" in self.model_fields_set:
            _dict['input_file_sha256'] = None

        # set to None if decompiler (nullable) is None
        # and model_fields_set contains the field
        if self.decompiler is None and "decompiler" in self.model_fields_set:
            _dict['decompiler'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BinaryDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instructions": obj.get("instructions"),
            "original_languages": OriginalLanguages.from_dict(obj["original_languages"]) if obj.get("original_languages") is not None else None,
            "platform": obj.get("platform"),
            "os_version": obj.get("os_version"),
            "input_file_sha256": obj.get("input_file_sha256"),
            "decompiler": Decompiler.from_dict(obj["decompiler"]) if obj.get("decompiler") is not None else None
        })
        return _obj


