# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from decompai_client.models.binary_state_paused import BinaryStatePaused
from decompai_client.models.binary_state_queued import BinaryStateQueued
from decompai_client.models.binary_state_ready import BinaryStateReady
from decompai_client.models.binary_state_uninitialized import BinaryStateUninitialized
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

BINARYSTATE_ONE_OF_SCHEMAS = ["BinaryStatePaused", "BinaryStateQueued", "BinaryStateReady", "BinaryStateUninitialized"]

class BinaryState(BaseModel):
    """
    BinaryState
    """
    # data type: BinaryStateUninitialized
    oneof_schema_1_validator: Optional[BinaryStateUninitialized] = None
    # data type: BinaryStateReady
    oneof_schema_2_validator: Optional[BinaryStateReady] = None
    # data type: BinaryStatePaused
    oneof_schema_3_validator: Optional[BinaryStatePaused] = None
    # data type: BinaryStateQueued
    oneof_schema_4_validator: Optional[BinaryStateQueued] = None
    actual_instance: Optional[Union[BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized]] = None
    one_of_schemas: Set[str] = { "BinaryStatePaused", "BinaryStateQueued", "BinaryStateReady", "BinaryStateUninitialized" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = BinaryState.model_construct()
        error_messages = []
        match = 0
        # validate data type: BinaryStateUninitialized
        if not isinstance(v, BinaryStateUninitialized):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BinaryStateUninitialized`")
        else:
            match += 1
        # validate data type: BinaryStateReady
        if not isinstance(v, BinaryStateReady):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BinaryStateReady`")
        else:
            match += 1
        # validate data type: BinaryStatePaused
        if not isinstance(v, BinaryStatePaused):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BinaryStatePaused`")
        else:
            match += 1
        # validate data type: BinaryStateQueued
        if not isinstance(v, BinaryStateQueued):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BinaryStateQueued`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in BinaryState with oneOf schemas: BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in BinaryState with oneOf schemas: BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into BinaryStateUninitialized
        try:
            instance.actual_instance = BinaryStateUninitialized.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BinaryStateReady
        try:
            instance.actual_instance = BinaryStateReady.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BinaryStatePaused
        try:
            instance.actual_instance = BinaryStatePaused.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BinaryStateQueued
        try:
            instance.actual_instance = BinaryStateQueued.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into BinaryState with oneOf schemas: BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into BinaryState with oneOf schemas: BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BinaryStatePaused, BinaryStateQueued, BinaryStateReady, BinaryStateUninitialized]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


