# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from decompai_client.models.analysis_accepted_event import AnalysisAcceptedEvent
from decompai_client.models.analysis_complete_event import AnalysisCompleteEvent
from decompai_client.models.copilot_clear_requested_event import CopilotClearRequestedEvent
from decompai_client.models.copilot_message_sent_event import CopilotMessageSentEvent
from decompai_client.models.copilot_open_event import CopilotOpenEvent
from decompai_client.models.copilot_stop_requested_event import CopilotStopRequestedEvent
from decompai_client.models.database_opened_event import DatabaseOpenedEvent
from decompai_client.models.initial_analysis_dismissed_event import InitialAnalysisDismissedEvent
from decompai_client.models.plugin_install_success_event import PluginInstallSuccessEvent
from decompai_client.models.plugin_loaded_event import PluginLoadedEvent
from decompai_client.models.quota_exhausted_dialog_shown_event import QuotaExhaustedDialogShownEvent
from decompai_client.models.quota_exhausted_event import QuotaExhaustedEvent
from decompai_client.models.swift_glow_close_event import SwiftGlowCloseEvent
from decompai_client.models.swift_glow_jump_from_line_event import SwiftGlowJumpFromLineEvent
from decompai_client.models.swift_glow_jump_to_line_event import SwiftGlowJumpToLineEvent
from decompai_client.models.swift_glow_open_event import SwiftGlowOpenEvent
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EVENT_ONE_OF_SCHEMAS = ["AnalysisAcceptedEvent", "AnalysisCompleteEvent", "CopilotClearRequestedEvent", "CopilotMessageSentEvent", "CopilotOpenEvent", "CopilotStopRequestedEvent", "DatabaseOpenedEvent", "InitialAnalysisDismissedEvent", "PluginInstallSuccessEvent", "PluginLoadedEvent", "QuotaExhaustedDialogShownEvent", "QuotaExhaustedEvent", "SwiftGlowCloseEvent", "SwiftGlowJumpFromLineEvent", "SwiftGlowJumpToLineEvent", "SwiftGlowOpenEvent"]

class Event(BaseModel):
    """
    Event
    """
    # data type: DatabaseOpenedEvent
    oneof_schema_1_validator: Optional[DatabaseOpenedEvent] = None
    # data type: PluginLoadedEvent
    oneof_schema_2_validator: Optional[PluginLoadedEvent] = None
    # data type: PluginInstallSuccessEvent
    oneof_schema_3_validator: Optional[PluginInstallSuccessEvent] = None
    # data type: AnalysisAcceptedEvent
    oneof_schema_4_validator: Optional[AnalysisAcceptedEvent] = None
    # data type: AnalysisCompleteEvent
    oneof_schema_5_validator: Optional[AnalysisCompleteEvent] = None
    # data type: InitialAnalysisDismissedEvent
    oneof_schema_6_validator: Optional[InitialAnalysisDismissedEvent] = None
    # data type: CopilotOpenEvent
    oneof_schema_7_validator: Optional[CopilotOpenEvent] = None
    # data type: CopilotMessageSentEvent
    oneof_schema_8_validator: Optional[CopilotMessageSentEvent] = None
    # data type: CopilotClearRequestedEvent
    oneof_schema_9_validator: Optional[CopilotClearRequestedEvent] = None
    # data type: CopilotStopRequestedEvent
    oneof_schema_10_validator: Optional[CopilotStopRequestedEvent] = None
    # data type: SwiftGlowOpenEvent
    oneof_schema_11_validator: Optional[SwiftGlowOpenEvent] = None
    # data type: SwiftGlowJumpToLineEvent
    oneof_schema_12_validator: Optional[SwiftGlowJumpToLineEvent] = None
    # data type: SwiftGlowJumpFromLineEvent
    oneof_schema_13_validator: Optional[SwiftGlowJumpFromLineEvent] = None
    # data type: SwiftGlowCloseEvent
    oneof_schema_14_validator: Optional[SwiftGlowCloseEvent] = None
    # data type: QuotaExhaustedEvent
    oneof_schema_15_validator: Optional[QuotaExhaustedEvent] = None
    # data type: QuotaExhaustedDialogShownEvent
    oneof_schema_16_validator: Optional[QuotaExhaustedDialogShownEvent] = None
    actual_instance: Optional[Union[AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent]] = None
    one_of_schemas: Set[str] = { "AnalysisAcceptedEvent", "AnalysisCompleteEvent", "CopilotClearRequestedEvent", "CopilotMessageSentEvent", "CopilotOpenEvent", "CopilotStopRequestedEvent", "DatabaseOpenedEvent", "InitialAnalysisDismissedEvent", "PluginInstallSuccessEvent", "PluginLoadedEvent", "QuotaExhaustedDialogShownEvent", "QuotaExhaustedEvent", "SwiftGlowCloseEvent", "SwiftGlowJumpFromLineEvent", "SwiftGlowJumpToLineEvent", "SwiftGlowOpenEvent" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Event.model_construct()
        error_messages = []
        match = 0
        # validate data type: DatabaseOpenedEvent
        if not isinstance(v, DatabaseOpenedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DatabaseOpenedEvent`")
        else:
            match += 1
        # validate data type: PluginLoadedEvent
        if not isinstance(v, PluginLoadedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PluginLoadedEvent`")
        else:
            match += 1
        # validate data type: PluginInstallSuccessEvent
        if not isinstance(v, PluginInstallSuccessEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PluginInstallSuccessEvent`")
        else:
            match += 1
        # validate data type: AnalysisAcceptedEvent
        if not isinstance(v, AnalysisAcceptedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AnalysisAcceptedEvent`")
        else:
            match += 1
        # validate data type: AnalysisCompleteEvent
        if not isinstance(v, AnalysisCompleteEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AnalysisCompleteEvent`")
        else:
            match += 1
        # validate data type: InitialAnalysisDismissedEvent
        if not isinstance(v, InitialAnalysisDismissedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InitialAnalysisDismissedEvent`")
        else:
            match += 1
        # validate data type: CopilotOpenEvent
        if not isinstance(v, CopilotOpenEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CopilotOpenEvent`")
        else:
            match += 1
        # validate data type: CopilotMessageSentEvent
        if not isinstance(v, CopilotMessageSentEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CopilotMessageSentEvent`")
        else:
            match += 1
        # validate data type: CopilotClearRequestedEvent
        if not isinstance(v, CopilotClearRequestedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CopilotClearRequestedEvent`")
        else:
            match += 1
        # validate data type: CopilotStopRequestedEvent
        if not isinstance(v, CopilotStopRequestedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CopilotStopRequestedEvent`")
        else:
            match += 1
        # validate data type: SwiftGlowOpenEvent
        if not isinstance(v, SwiftGlowOpenEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SwiftGlowOpenEvent`")
        else:
            match += 1
        # validate data type: SwiftGlowJumpToLineEvent
        if not isinstance(v, SwiftGlowJumpToLineEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SwiftGlowJumpToLineEvent`")
        else:
            match += 1
        # validate data type: SwiftGlowJumpFromLineEvent
        if not isinstance(v, SwiftGlowJumpFromLineEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SwiftGlowJumpFromLineEvent`")
        else:
            match += 1
        # validate data type: SwiftGlowCloseEvent
        if not isinstance(v, SwiftGlowCloseEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SwiftGlowCloseEvent`")
        else:
            match += 1
        # validate data type: QuotaExhaustedEvent
        if not isinstance(v, QuotaExhaustedEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QuotaExhaustedEvent`")
        else:
            match += 1
        # validate data type: QuotaExhaustedDialogShownEvent
        if not isinstance(v, QuotaExhaustedDialogShownEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QuotaExhaustedDialogShownEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Event with oneOf schemas: AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Event with oneOf schemas: AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DatabaseOpenedEvent
        try:
            instance.actual_instance = DatabaseOpenedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PluginLoadedEvent
        try:
            instance.actual_instance = PluginLoadedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PluginInstallSuccessEvent
        try:
            instance.actual_instance = PluginInstallSuccessEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AnalysisAcceptedEvent
        try:
            instance.actual_instance = AnalysisAcceptedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AnalysisCompleteEvent
        try:
            instance.actual_instance = AnalysisCompleteEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InitialAnalysisDismissedEvent
        try:
            instance.actual_instance = InitialAnalysisDismissedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CopilotOpenEvent
        try:
            instance.actual_instance = CopilotOpenEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CopilotMessageSentEvent
        try:
            instance.actual_instance = CopilotMessageSentEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CopilotClearRequestedEvent
        try:
            instance.actual_instance = CopilotClearRequestedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CopilotStopRequestedEvent
        try:
            instance.actual_instance = CopilotStopRequestedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SwiftGlowOpenEvent
        try:
            instance.actual_instance = SwiftGlowOpenEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SwiftGlowJumpToLineEvent
        try:
            instance.actual_instance = SwiftGlowJumpToLineEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SwiftGlowJumpFromLineEvent
        try:
            instance.actual_instance = SwiftGlowJumpFromLineEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SwiftGlowCloseEvent
        try:
            instance.actual_instance = SwiftGlowCloseEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QuotaExhaustedEvent
        try:
            instance.actual_instance = QuotaExhaustedEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QuotaExhaustedDialogShownEvent
        try:
            instance.actual_instance = QuotaExhaustedDialogShownEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Event with oneOf schemas: AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Event with oneOf schemas: AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AnalysisAcceptedEvent, AnalysisCompleteEvent, CopilotClearRequestedEvent, CopilotMessageSentEvent, CopilotOpenEvent, CopilotStopRequestedEvent, DatabaseOpenedEvent, InitialAnalysisDismissedEvent, PluginInstallSuccessEvent, PluginLoadedEvent, QuotaExhaustedDialogShownEvent, QuotaExhaustedEvent, SwiftGlowCloseEvent, SwiftGlowJumpFromLineEvent, SwiftGlowJumpToLineEvent, SwiftGlowOpenEvent]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


