# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from decompai_client.models.decompiler_note import DecompilerNote
from decompai_client.models.line_range import LineRange
from decompai_client.models.range import Range
from typing import Optional, Set
from typing_extensions import Self

class Function(BaseModel):
    """
    Function
    """ # noqa: E501
    address: Annotated[str, Field(strict=True)]
    type: Optional[StrictStr] = 'function'
    name: StrictStr
    has_known_name: Optional[StrictBool] = False
    mangled_name: Optional[StrictStr] = None
    inference_seq_number: Optional[StrictInt] = 0
    code: StrictStr
    calls: List[Annotated[str, Field(strict=True)]]
    data_refs_to: Optional[List[Annotated[str, Field(strict=True)]]] = None
    ranges: Optional[List[Range]] = None
    line_ranges: Optional[List[LineRange]] = None
    decompiler_notes: Optional[List[DecompilerNote]] = None
    analyze_as_swift: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["address", "type", "name", "has_known_name", "mangled_name", "inference_seq_number", "code", "calls", "data_refs_to", "ranges", "line_ranges", "decompiler_notes", "analyze_as_swift"]

    @field_validator('address')
    def address_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9a-f]{16}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{16}$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['function']):
            raise ValueError("must be one of enum values ('function')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Function from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ranges (list)
        _items = []
        if self.ranges:
            for _item_ranges in self.ranges:
                if _item_ranges:
                    _items.append(_item_ranges.to_dict())
            _dict['ranges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in line_ranges (list)
        _items = []
        if self.line_ranges:
            for _item_line_ranges in self.line_ranges:
                if _item_line_ranges:
                    _items.append(_item_line_ranges.to_dict())
            _dict['line_ranges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in decompiler_notes (list)
        _items = []
        if self.decompiler_notes:
            for _item_decompiler_notes in self.decompiler_notes:
                if _item_decompiler_notes:
                    _items.append(_item_decompiler_notes.to_dict())
            _dict['decompiler_notes'] = _items
        # set to None if mangled_name (nullable) is None
        # and model_fields_set contains the field
        if self.mangled_name is None and "mangled_name" in self.model_fields_set:
            _dict['mangled_name'] = None

        # set to None if line_ranges (nullable) is None
        # and model_fields_set contains the field
        if self.line_ranges is None and "line_ranges" in self.model_fields_set:
            _dict['line_ranges'] = None

        # set to None if analyze_as_swift (nullable) is None
        # and model_fields_set contains the field
        if self.analyze_as_swift is None and "analyze_as_swift" in self.model_fields_set:
            _dict['analyze_as_swift'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Function from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "type": obj.get("type") if obj.get("type") is not None else 'function',
            "name": obj.get("name"),
            "has_known_name": obj.get("has_known_name") if obj.get("has_known_name") is not None else False,
            "mangled_name": obj.get("mangled_name"),
            "inference_seq_number": obj.get("inference_seq_number") if obj.get("inference_seq_number") is not None else 0,
            "code": obj.get("code"),
            "calls": obj.get("calls"),
            "data_refs_to": obj.get("data_refs_to"),
            "ranges": [Range.from_dict(_item) for _item in obj["ranges"]] if obj.get("ranges") is not None else None,
            "line_ranges": [LineRange.from_dict(_item) for _item in obj["line_ranges"]] if obj.get("line_ranges") is not None else None,
            "decompiler_notes": [DecompilerNote.from_dict(_item) for _item in obj["decompiler_notes"]] if obj.get("decompiler_notes") is not None else None,
            "analyze_as_swift": obj.get("analyze_as_swift")
        })
        return _obj


