# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from decompai_client.models.function_overview import FunctionOverview
from decompai_client.models.name import Name
from decompai_client.models.not_swift import NotSwift
from decompai_client.models.parameter_type import ParameterType
from decompai_client.models.parameters_mapping import ParametersMapping
from decompai_client.models.return_type import ReturnType
from decompai_client.models.struct_definition import StructDefinition
from decompai_client.models.swift_function import SwiftFunction
from decompai_client.models.variables_mapping import VariablesMapping
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

INFERENCE_ONE_OF_SCHEMAS = ["FunctionOverview", "Name", "NotSwift", "ParameterType", "ParametersMapping", "ReturnType", "StructDefinition", "SwiftFunction", "VariablesMapping"]

class Inference(BaseModel):
    """
    Inference
    """
    # data type: Name
    oneof_schema_1_validator: Optional[Name] = None
    # data type: FunctionOverview
    oneof_schema_2_validator: Optional[FunctionOverview] = None
    # data type: ParametersMapping
    oneof_schema_3_validator: Optional[ParametersMapping] = None
    # data type: VariablesMapping
    oneof_schema_4_validator: Optional[VariablesMapping] = None
    # data type: ParameterType
    oneof_schema_5_validator: Optional[ParameterType] = None
    # data type: ReturnType
    oneof_schema_6_validator: Optional[ReturnType] = None
    # data type: SwiftFunction
    oneof_schema_7_validator: Optional[SwiftFunction] = None
    # data type: StructDefinition
    oneof_schema_8_validator: Optional[StructDefinition] = None
    # data type: NotSwift
    oneof_schema_9_validator: Optional[NotSwift] = None
    actual_instance: Optional[Union[FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping]] = None
    one_of_schemas: Set[str] = { "FunctionOverview", "Name", "NotSwift", "ParameterType", "ParametersMapping", "ReturnType", "StructDefinition", "SwiftFunction", "VariablesMapping" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Inference.model_construct()
        error_messages = []
        match = 0
        # validate data type: Name
        if not isinstance(v, Name):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Name`")
        else:
            match += 1
        # validate data type: FunctionOverview
        if not isinstance(v, FunctionOverview):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FunctionOverview`")
        else:
            match += 1
        # validate data type: ParametersMapping
        if not isinstance(v, ParametersMapping):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ParametersMapping`")
        else:
            match += 1
        # validate data type: VariablesMapping
        if not isinstance(v, VariablesMapping):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VariablesMapping`")
        else:
            match += 1
        # validate data type: ParameterType
        if not isinstance(v, ParameterType):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ParameterType`")
        else:
            match += 1
        # validate data type: ReturnType
        if not isinstance(v, ReturnType):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReturnType`")
        else:
            match += 1
        # validate data type: SwiftFunction
        if not isinstance(v, SwiftFunction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SwiftFunction`")
        else:
            match += 1
        # validate data type: StructDefinition
        if not isinstance(v, StructDefinition):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StructDefinition`")
        else:
            match += 1
        # validate data type: NotSwift
        if not isinstance(v, NotSwift):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NotSwift`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Inference with oneOf schemas: FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Inference with oneOf schemas: FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Name
        try:
            instance.actual_instance = Name.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FunctionOverview
        try:
            instance.actual_instance = FunctionOverview.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ParametersMapping
        try:
            instance.actual_instance = ParametersMapping.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into VariablesMapping
        try:
            instance.actual_instance = VariablesMapping.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ParameterType
        try:
            instance.actual_instance = ParameterType.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReturnType
        try:
            instance.actual_instance = ReturnType.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SwiftFunction
        try:
            instance.actual_instance = SwiftFunction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StructDefinition
        try:
            instance.actual_instance = StructDefinition.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NotSwift
        try:
            instance.actual_instance = NotSwift.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Inference with oneOf schemas: FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Inference with oneOf schemas: FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FunctionOverview, Name, NotSwift, ParameterType, ParametersMapping, ReturnType, StructDefinition, SwiftFunction, VariablesMapping]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


