# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from decompai_client.models.quota import Quota
from typing import Optional, Set
from typing_extensions import Self

class PluginDetails(BaseModel):
    """
    Complete environment details sent with every event.
    """ # noqa: E501
    uid: StrictStr
    quota: Quota
    decompiler: StrictStr
    decompiler_version: StrictStr
    os_type: StrictStr
    os_version: Optional[StrictStr]
    plugin_version: StrictStr
    install_id: StrictStr
    session_id: StrictStr
    __properties: ClassVar[List[str]] = ["uid", "quota", "decompiler", "decompiler_version", "os_type", "os_version", "plugin_version", "install_id", "session_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PluginDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quota
        if self.quota:
            _dict['quota'] = self.quota.to_dict()
        # set to None if os_version (nullable) is None
        # and model_fields_set contains the field
        if self.os_version is None and "os_version" in self.model_fields_set:
            _dict['os_version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PluginDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uid": obj.get("uid"),
            "quota": Quota.from_dict(obj["quota"]) if obj.get("quota") is not None else None,
            "decompiler": obj.get("decompiler"),
            "decompiler_version": obj.get("decompiler_version"),
            "os_type": obj.get("os_type"),
            "os_version": obj.get("os_version"),
            "plugin_version": obj.get("plugin_version"),
            "install_id": obj.get("install_id"),
            "session_id": obj.get("session_id")
        })
        return _obj


