# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SwiftRejectionReason(str, Enum):
    """
    SwiftRejectionReason
    """

    """
    allowed enum values
    """
    TOO_SHORT = 'too_short'
    HAS_NON_SWIFT_NAME = 'has_non_swift_name'
    COMPILER_GENERATED = 'compiler_generated'
    DOESNT_LOOK_LIKE_SWIFT = 'doesnt_look_like_swift'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SwiftRejectionReason from a JSON string"""
        return cls(json.loads(json_str))


