# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from decompai_client.models.expired_usage import ExpiredUsage
from decompai_client.models.limited_usage import LimitedUsage
from decompai_client.models.unlimited_usage import UnlimitedUsage
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

USAGERESPONSE_ONE_OF_SCHEMAS = ["ExpiredUsage", "LimitedUsage", "UnlimitedUsage"]

class UsageResponse(BaseModel):
    """
    UsageResponse
    """
    # data type: ExpiredUsage
    oneof_schema_1_validator: Optional[ExpiredUsage] = None
    # data type: UnlimitedUsage
    oneof_schema_2_validator: Optional[UnlimitedUsage] = None
    # data type: LimitedUsage
    oneof_schema_3_validator: Optional[LimitedUsage] = None
    actual_instance: Optional[Union[ExpiredUsage, LimitedUsage, UnlimitedUsage]] = None
    one_of_schemas: Set[str] = { "ExpiredUsage", "LimitedUsage", "UnlimitedUsage" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UsageResponse.model_construct()
        error_messages = []
        match = 0
        # validate data type: ExpiredUsage
        if not isinstance(v, ExpiredUsage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExpiredUsage`")
        else:
            match += 1
        # validate data type: UnlimitedUsage
        if not isinstance(v, UnlimitedUsage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UnlimitedUsage`")
        else:
            match += 1
        # validate data type: LimitedUsage
        if not isinstance(v, LimitedUsage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LimitedUsage`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UsageResponse with oneOf schemas: ExpiredUsage, LimitedUsage, UnlimitedUsage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UsageResponse with oneOf schemas: ExpiredUsage, LimitedUsage, UnlimitedUsage. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ExpiredUsage
        try:
            instance.actual_instance = ExpiredUsage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UnlimitedUsage
        try:
            instance.actual_instance = UnlimitedUsage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into LimitedUsage
        try:
            instance.actual_instance = LimitedUsage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UsageResponse with oneOf schemas: ExpiredUsage, LimitedUsage, UnlimitedUsage. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UsageResponse with oneOf schemas: ExpiredUsage, LimitedUsage, UnlimitedUsage. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExpiredUsage, LimitedUsage, UnlimitedUsage]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


